---

- hosts: all
  become: true
  tasks:

  - name: install net-tools package
    yum:
      name: net-tools
      state: latest
    when: ansible_distribution == "RedHat" 

  - name: install php package
    yum:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php package
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

