---

- hosts: all
  become: true
  tasks:

  - name: install apache2 or httpd and php packages
    package:  # generic package manager , it can be yum, apt, apt-get and so on
      name:
        - "{{ apache_package }}" # the se are variable whhich are defined in the inventory       
        - "{{ php_package }}"    # same here
      state: latest
      update_cache: yes
   # when: ansible_distribution == "RedHat" we dont need as OS is covered


 


