---

- hosts: all
  become: true
  tasks:

  - name: remove net-tools package
    yum:
      name: net-tools
      state: absent
  - name: remove make package
    yum:
      name: make
      state: absent

